# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='150x150px', upload_to='images/%Y/%m/%d', verbose_name='Ссылка картинки'),
        ),
    ]
