# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180114_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_file',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d', verbose_name='Файл'),
        ),
    ]
